inputDirectory: input
outputDirectory: output
templateDirectory: template
title: My blog
ga: G-78HB0G4J5S
theme: SolidState
description: 
additionalItems: 
additionalFooterLinks: 
additionalNavLinks: 
facebook: 
twitter: 
linkedin: 
email: 
tel: 
generic: 
  just-software:
    id: 7gfBiYPjyjHt3X73eL9u
    key: ojVkM+GtcXMc/alv7rugBYBFEUuJGaMLkNPvmng3IrSRTO7qYwnPOLHB1PvELv5bTMQToPHNb+XtjyxJEDMFtFH8QQApFrudtZA8qgvd+plFY5luCRd1maU17ihQCiUf/qKLzoIOmlercqQzl2mY/gP8BW2RWE1sR19q6BfYDs4U9wpN70exI9BVIidhvGHOMgFzD2J+h0/ufzhQYR50kwZDDa96somzRYVOf5URJSO4J8hdVANG+mfQYgA+/bMUxgL3lGi7Gtaot1m8Lp6KJlMuL8vayJmGjre/Wfivwm4GVB+rZNW/Rz8NFNzoHzzzl8pslXO+/A+dM3Eqm4WNaRK85C69HiQldAIe/4suLrJMCmqnwP860VtznZju40KSRYF/xJgd0FC1qTaDMyCVrLBDT9BzvJgok6hyIfx97F+9Xk9bsWSSbJNuYJH1sY5i4VtY2+0lNT0rurRwuBjK+mPDEJjEi7Hdc4BN7lAw1bCjGymaQ0yfE3rVH07gWbQR
