inputDirectory: input
outputDirectory: output
templateDirectory: template
title: My blog
ga: 
theme: SolidState
description: 
additionalItems: 
additionalFooterLinks: 
additionalNavLinks: 
facebook: 
twitter: 
linkedIn: 
email: 
tel: 
